{% set name = "csaps" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/csaps-{{ version }}.tar.gz
  sha256: 66403fa0cff7a9bf77c29334035bc3bd9312224a4f58c8c7d07a7f9dfb8cf3f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1.11.0,<2
    - scipy >=1.0.0,<2

test:
  imports:
    - csaps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/espdev/csaps
  summary: Cubic spline approximation (smoothing)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smithsp
    - kalling
