{% set name = "csaps" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/csaps-{{ version }}.tar.gz
  sha256: 346569028eedc6102ac4bcd799aed7b5150e587599719d91b589e21202c25c7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0
    - numpy >=1.11.0,<2
    - scipy >=1.0.0,<2

test:
  imports:
    - csaps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/espdev/csaps
  summary: Cubic spline approximation (smoothing)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smithsp
    - kalling
